<?php
/**
 * This is a module generated by the MW Page Builder
 * @module content
 */

function module_backend_render() {



}

function module_content_render() {

    ?>

    <div class="module module-content">
        <h2>The content module</h2>
        <p>Here goes all the content from the content module render function.</p>
        <p>It's really good content, but we don't know yet, how to parse data into it.</p>
        <p>We're gonna find out though!</p>
    </div>

    <?php

}

createModule('content', 'module_content_render');