<?php
/**
 * This is a module generated by the MW Page Builder
 * @module content
 */

class MwpbContentModule extends MwpbModule {

    public $name = "content";

    public function __construct() {
        parent::__construct($this->name, array($this, 'frontend_render'));
    }

    public function frontend_render() {
        echo "TESTING!!!";
    }

    public function  backend_render() {

    }

} new MwpbContentModule();